version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    restart: on-failure
    ports:
      - 8001:8001
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data:
